apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhtap-test-sept30-1 
  janus-idp.io/tekton: rhtap-test-sept30-1
  backstage.io/kubernetes-id: rhtap-test-sept30-1
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: rhtap-test-sept30-1
resources: 
- application-dev.yaml