kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhtap-test-sept30-1-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rhtap-test-sept30-1-dsp-job
    namespace: rhtap-app-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhtap-test-sept30-1-dsp-job-role