apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhtap-test-sept30-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/rhtap-test-sept30-1:7b47bf83c0fab4948f47fa974fc10288d906220a@sha256:a8703970567ad888bbbe6bcdf04a0fd7cba9185e0aa7e6ca626f25649d6134ff # use pre-built to bootstrap 
          name: app-inference
