---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rhtap-test-sept30-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-test-sept30-1 
  name: rhtap-test-sept30-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi